### ISSUE TITLE
Unsplash API rate increase checklist

### ISSUE THREAD

**Issue by CKBoytGT** [BJThompson12/Sea-Wolves#61]
- [x] Set up relay
- [x] Include link/credit to Unsplash main site along with photographer credit
- [ ] Delete old key after deploying updated site
